# Generated by Django 5.2.17 on 2026-09-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Id used by the API and UI.', max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('provider', models.CharField(choices=[('sagemaker', 'AWS SageMaker endpoint'), ('openai', 'OpenAI-compatible server (vLLM, Ollama, LM Studio, ...)'), ('mock', 'Mock (fake answers, for development)')], max_length=20)),
                ('model_id', models.CharField(blank=True, help_text='Sent as "model" in each request, e.g. Qwen/Qwen3-VL-8B-Instruct-FP8 or llama3.2:3b.', max_length=200)),
                ('base_url', models.CharField(blank=True, help_text='e.g. http://ollama:11434/v1', max_length=300)),
                ('api_key', models.CharField(blank=True, max_length=300)),
                ('endpoint_name', models.CharField(blank=True, max_length=63)),
                ('endpoint_config_name', models.CharField(blank=True, help_text='The controller creates the endpoint from this configuration.', max_length=63)),
                ('region', models.CharField(blank=True, help_text='Defaults to AWS_REGION.', max_length=30)),
                ('scaling', models.CharField(choices=[('on_demand', 'On demand: start when used, delete when idle'), ('always_on', 'Always on'), ('off', 'Off: keep the endpoint deleted'), ('manual', 'Manual: the controller never touches it')], default='manual', max_length=20)),
                ('idle_minutes', models.PositiveIntegerField(default=30)),
                ('hourly_cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('vision', models.BooleanField(default=False, help_text='Accepts images directly.')),
                ('ocr', models.BooleanField(default=False, help_text='Preferred model for the OCR tool.')),
                ('context_window', models.PositiveIntegerField(default=8192)),
                ('max_output_tokens', models.PositiveIntegerField(default=2048)),
                ('temperature', models.FloatField(default=0.7)),
                ('is_default', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=100)),
                ('managed_by_env', models.BooleanField(default=False, editable=False, help_text='Created from LLM_MODELS. sync_models overwrites its settings.')),
                ('endpoint_status', models.CharField(blank=True, max_length=30)),
                ('endpoint_error', models.TextField(blank=True)),
                ('status_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('wake_requested_at', models.DateTimeField(blank=True, null=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_stopped_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM model',
                'ordering': ['sort', 'name'],
            },
        ),
    ]
